/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICustomStyleDictionary: typeof import('~icons/custom/style-dictionary')['default']
    ICustomTheemo: typeof import('~icons/custom/theemo')['default']
  }
}
