name: CI (Figma Theemo)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - packages/figma-theemo/**
      - pnpm-lock.yaml
  push:
    branches:
      - main

jobs:
  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Tools
  #       uses: volta-cli/action@v1
  #     - name: Cache pnpm modules
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.pnpm-store
  #         key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-
  #     - uses: pnpm/action-setup@v2.2.2
  #       with:
  #         version: latest

  #     - run: pnpm install
  #     - run: pnpm --filter 'theemo' lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Tools
        uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - run: pnpm install
      - run: pnpm --filter 'figma-theemo' test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Tools
        uses: volta-cli/action@v1
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - run: pnpm install
      - run: pnpm --filter 'figma-theemo' build
