name: 'Coverage'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: volta-cli/action@v1
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
      - name: Collect Coverage and Submit to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: yarn coverage
          coverageLocations: |
            ${{github.workspace}}/packages/theemo/coverage/lcov.info:lcov
