name: 'Coverage'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/@theemo/**'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - name: Collect Coverage and Submit to CodeClimate
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: pnpm test
          coverageLocations: |
            ${{github.workspace}}/coverage/clover.xml:clover
