name: 'Coverage'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/@theemo/**'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Collect Coverage and Submit to CodeClimate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: pnpm test
          coverageLocations: |
            ${{github.workspace}}/coverage/clover.xml:clover
