# This is a basic workflow to help you get started with Actions

name: Deploy docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: install theemo
      run: yarn
    
    - name: build api
      run: yarn api

    # Runs a set of commands using the runners shell
    - name: install docusaurus
      run: cd website && yarn
    
    - name: build docusaurus
      run: cd website && yarn build
      
    - name: deploy docusaurus
      run: |
        git config --global user.name "gh-actions"
        git config --global user.email "actions@github.com"
        cd website && GIT_USER=$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }} USE_SSH=false yarn deploy
