# For every push to the master branch, this checks if the release-plan was
# updated and if it was it will publish stable npm packages based on the
# release plan

name: Publish Stable

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".release-plan.json"

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: "NPM Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup
        # we are doing this to make sure theat the gloabally installed npm is new enough to support OIDC
      - name: Install latest npm (for Trusted Publishing)
        run: npm install -g npm@latest
      - name: Publish to NPM
        run: NPM_CONFIG_PROVENANCE=true pnpm release-plan publish
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
